---
title: "créer une application web interactive avec R et Shiny"
author: "Yann Ryan"
translator: "Damien Belvèze"
date: "2024-08-30"
output:
  html_document:
    toc: true
    theme: united
---

Cette leçon montre comment construire une carte web interactive avec R et la bibliothèque SHiny. Dans cette leçon, vous concevrez et implémenterez une application simple consistant en un carroussel qui permet à l'internaute en sélectionnant un intervalle de dates d'afficher un ensemble de points correspondants sur une carte interactive.


# Introduction

Cette leçon montre comment construire une carte web interactive en utilisant Shiny. Shiny est une bibliothèque (en anglais, *library*, un ensemble de fonctions) destinée à la programmation avec R. Elle est conçue pour faciliter le développement d'applications web qui permettent aux utilisateurs et utilisatrices d'interagir avec le code dans R en utilisant les éléments d'une interface dans son navigateur, comme des carroussels, des menus déroulants, etc. Dans cette leçon, vous allez concevoir et implémenter une simple application consistant en un carroussel qui permettra aux internautes de sélectionner un intervalle de dates, sélection qui activera du code dans R pour faire s'afficher des points correspondant à ces dates sur une carte interactive. 

# Objectifs de la leçon

A la suite de cette leçon, vous saurez: 

- Créer une application de base avec Shiny    
- maîtriser la disposition de l'interface de Shiny et sa conception de base
- la théorie et la pratique de la "programmation réactive" telle qu'implémentée dans les applications faites avec Shiny. Particulièrement, vous apprendrez comment utiliser Shiny pour répondre à certaines actions et comment ces actions en entrée sont connectées à des actions en sortie sur l'application

---
Notez que cette leçon ne vous apprend pas à coder avec R en dehors de ce qui est nécessaire pour créer une application web, il ne couvre pas non plus la publication sur le web d'une application entièrement réalisée. une connaissance basique de R, notamment l'usage du *tidyverse* vous sera très utile.
---

# Interfaces graphiques et Humanités numériques

Les [Interfaces Usager Graphiques](https://perma.cc/8SYH-TX26) (GUI) et les éléments interactifs peuvent aider à rendre plus accessibles et plus lisibles des travaux scientifiques basés sur des données. A titre d'exemple, les historiens qui travaillent avec des données à large échelle peuvent avoir besoin de montrer comment une variable peut changer à travers le temps. Une carte interactive dotée d'une frise paramétrable est dans certains cas plus facile à lire et offre plus de granularité qu'une série de cartes statiques. Permettre à l'utilisateur et l'utilisatrice de régler les paramètres de la visualisation permet d'éviter certains biais qu'on rencontre souvent dans les visualisations qui utilisent des données chronologiques (par exemple, le fait de réaliser des cartes successives avec un intervalle fixe de 1à ans).

Bien des projets de recherche donnent lieu à des produits sous la forme d'objets interactifs. Parmi les exemples à citer, on trouve la [visualisation des réseaux du pouvoir des Tudors](https://tudornetworks.net/) dans les *Tudor State Papers*, la phylogénie interactive de la Presse britannique et pour citer un exemple qui utilise Shiny, l'application [GeoNewsMiner](https://utrecht-university.shinyapps.io/GeoNewsMiner) qui affiche les lieux géocodés cités dans un corpus de titres de presse. Les applications interactives peuvent aussi constituer des outils intéressants pour les archivistes : les chercheurs des Archives Nationales Britanniques ont créé [une app avec Shiny](https://perma.cc/C6U5-PYHF) qui mesure le niveau de risques encouru par une collection numérique à travers une série de questions posées par les usagers. 

Un autre cas d'usage typique d'applications interactives consiste à faciliter l'exploration de votre jeu de données
sans même qu'il soit question de rendre l'application elle-même disponible au public. Il n'y a qu'à utilise les visualisations interactives des données pour y faire des constats intéressants ou bien comme point de départ de recherches futures. Dans cette optique, l'interactivité peut être particulièrement utile pour assister l'exploration des données et la découverte de constantes au sein de jeux de données à grande échelle. 

# Options pour crées des interfaces graphiques

Il y a bien des manières d'approcher le développement de visualisations interactives comme celles des exemples mentionnés plus haut. L'une consiste à apprendre à maîtriser un outil spécialisé dans la manipulation de pages web en réponse à l'entrée de données, on pense ici à la [bibliothèque Javascript D3](https://perma.cc/BG9S-KPJE). Une seconde option consisterait à utiliser les outils existants qui sont basés sur le web, certains généralistes comme [Tableau](https://perma.cc/M6Y9-9ZCP) ou [Rawgraphs](https://perma.cc/TAA2-W7WA), ou certains plus spécialisés comme [Palladio](https://perma.cc/2W5A-PBJU) ou [Gephi](https://perma.cc/SS9Z-6DAG). Une troisième approche pourrait nous inciter à utiliser les [Jupyter Notebooks](https://perma.cc/CX23-VTAK), qui vous permet de partager du code interactif, et même, au moyen de quelques [paquets additionnels](https://perma.cc/ESA5-9MEJ), de créer une interface utilisateur.  

Cette leçon traite d'une quatrième approche : réaliser des applications interactives avec une interface utilisateur qui repose sur une bibliothèque adaptée à un langage de programmation généraliste, une bibliothèque comme [Bokeh](https://perma.cc/LXR5-BYC9) ou [Dash](https://perma.cc/J7T9-EHTJ) pour Python, ou bien -ce qu'on va utiliser dans ce tutoriel- [Shiny](https://perma.cc/CK9W-VRKN) pour R. Python et R sont tous les deux des langages de programmation open source, versatiles et largement utilisés disposant de communautés actives et une large collection de paquets réalisés par des Tiers. En bien des occasions, utiliser ces langages comme base d'applications interactives a tout son sens. Essentiellement, ces paquets agissent comme des interfaces interactives pour le langage de programmation, ce qui permet la création de carroussels, de sélecteurs, etc. Tout cela peut ensuite être utilisé comme porte d'entrée pour changer de façon dynamique des bouts de code. La plupart du temps, cela ne requiert aucune expertise de la part de l'utilisateur final. Dans la mesure où ces applications sont conçues pour fonctionner dans le navigateur, elles peuvent fonctionner sur toutes les plateformes et sont faciles à partager.

# Shiny et la programmation réactive

Shiny est basée sur le concept dit de *réactivité*. Habituellement, quand on code, on assigne une valeur spécifique à une variable, disons ```x = 5```. Dans la *programmation réactive*, la variable est dépendante d'une entrée différente à chaque fois, généralement fixée par l'utilisateur (un partir d'un curseur pour faire défiler du texte ou d'un menu déroulant par exemple). Le code est réceptif aux changements qui affectent ces variables réactives, et chaque fois que ces variables spéciales mutent, tous les caractères en sortie qu'elles sont conçues pour générer se mettent à jour automatiquement. 

Cependant, ces mises à jour n'ont lieu que dans des **contextes réactifs**. Shiny a trois contextes réactifs importants : les fonctions ```render*``` qui sont utilisées pour créer des objets R et les afficher dans l'app, ```observe({})``` et ```reactive({})```. Dans ce tutoriel, vous utiliserez la réactivité pour créer un *dataframe* récapitulatif de titres de journaux (et leurs dates de parution), qui se mettra à jour automatique à partir des dates entrées par l'utilisateur. Ailleurs dans votre app, vous utiliserez une fonction ```render*``` pour faire apparaître une carte qui sera sensible à ce data frame réactif et intégrera chaque mise à jour détectée.

# Avantages et limites de l'usages de Shiny

L'avantage de cette approche est que créer des applications Shiny est *relativement* simple si on connaît déjà R, et l'ensemble des bibliothèques et fonctionnalités de R peut être pris en charge par Shiny. Dans certaines circonstances, il peut être préférable d'apprendre un nouveau langage en partant de zéro. Si vous avez déjà de l'expérience avec R et juste une petite connaissance de Shiny, vous pouvez créer des applications utiles et très complexes, qui couvrent tout le champ entre les cartes et les analyses sous forme de graphes, depuis les [modèles d'apprentissage machine](https://perma.cc/YAX3-RZZP), jusqu'à des consoles riches en fonctionnalités. Si vous savez le programmer avec R, vous pourrez probablement le rendre interactif avec Shiny. Le procédé pour créer une interface Shiny est très flexible et très facile à personnaliser, cela signifie qu'il est relativement rapide de faire une application dans un format susceptible d'être embarqué dans le site d'un projet au moyen d'iframes : voyez le projet [Mapping the Gay Guides] (https://www.mappingthegayguides.org/map/) par exemple.  

Il y a toutefois des inconvénients à prendre en considération. Pour celles et ceux qui n'ont pas l'intention d'utiliser un langage tel que R à d'autres occasions dans leur travail, l'apprendre juste pour produire des apps Shiny peut paraître démesuré. mais de loin la façon la plus simple de publier sur le web votre application une fois achevée est d'utiliser un service appelé *shinyapps.io*.
Shinyapps.io est un produit commercial qui propose un accès gratuit mais limité en nombre d'heures (25) et après vous devrez payer un abonnement mensuel. Vous pouvez *exécuter* Shiny sur votre propre serveur (ou bien en passant par quelque chose comme les *Amazon Web Services*), mais c'est un procédé qui est exigeant pour l'utilisateur et requiert de sa part un plutôt bon niveau de maîtrise dans la configuration de serveurs web. Il vous faut garder cela à l'esprit si vous pensez utiliser Shiny pour produire une interface publique particulièrement si vous pensez que cette interface pourrait générer beaucoup de trafic et des usages massifs. En guise d'alternative, certaines des fonctionnalités de Shiny peuvent être répliquées dans une simple page HTML en utilisant le paquet R [crosstalk](https://rstudio.github.io/crosstalk/index.html.

# Arrière plan historique et données






l
